---
- name: update grub config file
  hosts: all
  user: ansible
  tasks:
          - name: update grub config
            lineinfile:
                    path: /etc/default/grub
                    regexp: '^(GRUB_CMDLINE_LINUX=(?!.* [net\.ifnames|biosdevname])\"[^\"]+)(\".*)'
                    backrefs: yes
                    line: '\1 net.ifnames=0 biosdevname=0\2'
          - name: generate new grub config script and place to ansible user home.
            command: grub2-mkconfig -o /home/ansible/grub.cfg
...
